// Mock data for comments
export const mockComments = [
  {
    id: 1,
    name: "Sarah Johnson",
    username: "@sarahj",
    avatar: "/avatars/sarah.jpg",
    time: "2 hours ago",
    text: "This is such an insightful post! I've been struggling with this exact issue and your solution really helped me understand the concept better.",
    likes: 24,
    replies: [
      {
        id: 2,
        name: "Mike Chen",
        username: "@mikechen",
        avatar: "/avatars/mike.jpg",
        time: "1 hour ago",
        text: "I agree! The examples provided are really clear and easy to follow.",
        likes: 8,
      },
      {
        id: 3,
        name: "Emma Wilson",
        username: "@emmaw",
        avatar: "/avatars/emma.jpg",
        time: "45 minutes ago",
        text: "Thanks for sharing this. I bookmarked it for future reference!",
        likes: 5,
      },
    ],
  },
  {
    id: 4,
    name: "Alex Rodriguez",
    username: "@alexr",
    avatar: "/avatars/alex.jpg",
    time: "3 hours ago",
    text: "Great explanation! Could you also cover the edge cases that might occur in production environments?",
    likes: 15,
    replies: [
      {
        id: 5,
        name: "David Kim",
        username: "@davidk",
        avatar: "/avatars/david.jpg",
        time: "2 hours ago",
        text: "That's a great question. I'd love to see more about error handling too.",
        likes: 3,
      },
    ],
  },
  {
    id: 6,
    name: "Lisa Thompson",
    username: "@lisat",
    avatar: "/avatars/lisa.jpg",
    time: "4 hours ago",
    text: "This saved me hours of debugging! Thank you so much for taking the time to write this detailed explanation. 🙏",
    likes: 32,
  },
  {
    id: 7,
    name: "James Park",
    username: "@jamespark",
    avatar: "/avatars/james.jpg",
    time: "5 hours ago",
    text: "I implemented this approach in my project and it works perfectly. The performance improvement is noticeable!",
    likes: 18,
    replies: [
      {
        id: 8,
        name: "Rachel Green",
        username: "@rachelg",
        avatar: "/avatars/rachel.jpg",
        time: "4 hours ago",
        text: "What kind of performance improvements did you see? I'm curious about the metrics.",
        likes: 7,
      },
      {
        id: 9,
        name: "James Park",
        username: "@jamespark",
        avatar: "/avatars/james.jpg",
        time: "3 hours ago",
        text: "@rachelg About 40% faster load times and reduced memory usage by 25%. Pretty significant!",
        likes: 12,
      },
    ],
  },
  {
    id: 10,
    name: "Maria Garcia",
    username: "@mariag",
    avatar: "/avatars/maria.jpg",
    time: "6 hours ago",
    text: "As a beginner, this was exactly what I needed. The step-by-step approach makes it so much easier to understand.",
    likes: 9,
  },
  {
    id: 11,
    name: "Tom Wilson",
    username: "@tomw",
    avatar: "/avatars/tom.jpg",
    time: "8 hours ago",
    text: "Have you considered the accessibility implications of this approach? Would love to hear your thoughts on making it more inclusive.",
    likes: 14,
    replies: [
      {
        id: 12,
        name: "Anna Lee",
        username: "@annal",
        avatar: "/avatars/anna.jpg",
        time: "7 hours ago",
        text: "Great point! ARIA labels and keyboard navigation should definitely be considered.",
        likes: 6,
      },
    ],
  },
  {
    id: 13,
    name: "Chris Brown",
    username: "@chrisb",
    avatar: "/avatars/chris.jpg",
    time: "1 day ago",
    text: "This is gold! I've been looking for a solution like this for weeks. Can't wait to try it out in my next project.",
    likes: 21,
  },
];

// Alternative mock data with placeholder avatars (using placeholder services)
export const mockCommentsWithPlaceholders = [
  {
    id: 1,
    name: "Sarah Johnson",
    username: "@sarahj",
    avatar:
      "https://images.unsplash.com/photo-1494790108755-2616b612b786?w=32&h=32&fit=crop&crop=face",
    time: "2 hours ago",
    text: "This is such an insightful post! I've been struggling with this exact issue and your solution really helped me understand the concept better.",
    likes: 24,
    replies: [
      {
        id: 2,
        name: "Mike Chen",
        username: "@mikechen",
        avatar:
          "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=32&h=32&fit=crop&crop=face",
        time: "1 hour ago",
        text: "I agree! The examples provided are really clear and easy to follow.",
        likes: 8,
      },
    ],
  },
  {
    id: 3,
    name: "Emma Wilson",
    username: "@emmaw",
    avatar:
      "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=32&h=32&fit=crop&crop=face",
    time: "3 hours ago",
    text: "Thanks for sharing this. I bookmarked it for future reference!",
    likes: 15,
  },
  {
    id: 4,
    name: "Alex Rodriguez",
    username: "@alexr",
    avatar:
      "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=32&h=32&fit=crop&crop=face",
    time: "4 hours ago",
    text: "Great explanation! Could you also cover the edge cases that might occur in production environments?",
    likes: 12,
  },
];
