import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { AppSidebar } from "./components/sidebar";

import { queryClient } from "@/service/queryClient";
import { QueryClientProvider } from "@tanstack/react-query";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased">
        <QueryClientProvider client={queryClient}>

        <SidebarProvider defaultOpen={false}>
          <div className="flex w-full min-h-screen">
            <AppSidebar />
            <main className="flex-1 overflow-x-hidden bg-white dark:bg-[#09090b]">
              <div>
                <SidebarTrigger className="md:hidden mb-4" />
                {children}
              </div>
            </main>
          </div>
        </SidebarProvider>
        </QueryClientProvider>
 
      </body>
    </html>
  );
}
